### PR TITLE
Added color options

### PR DESCRIPTION
**Pull request by mcharo**
It's my first time submitting a PR, so please excuse any missteps.  
Added:
- [MyStickyNote]::SetColor for setting the note's color

Modified:
- [MyStickyNote]::NewNote to set the color
- New-StickyNote to accept Color parameter
- Set-StickyNote to accept Color parameter

Tested on Windows 10 (PS 5.0.10586.494).

### CODE REVIEW

**Comment by jdhitsolutions** [comment]
These look like some interesting ideas that I wouldn't have thought of not being a .NET developer. Might tweak them a bit further.

**Comment by jdhitsolutions** [comment]
What version of Windows did you test your changes on?

**Comment by mcharo** [comment]
I'm running Windows 10.0.10586. The RTF manipulation might be too fiddly but it gave more control over the text.

**Comment by jdhitsolutions** [comment]
I think Windows 10 added a few things. The keyboard shortcuts don't seem to work in Windows 8.1. I'll have to think about how to handle this.

**Comment by jdhitsolutions** [comment]
Windows 10 turned StickyNotes into a modern app which changes a lot.

**Comment by mcharo** [comment]
Which keyboard shortcuts aren't working?  I don't have a Windows 8.1 machine running at the moment, but I briefly looked at the Windows 7 version of StickyNotes and didn't notice immediate differences between it and the Windows 10 version.  I'll try to get an 8.1 VM up and running.

**Comment by jdhitsolutions** [comment]
The modern app running on Windows 10 doesn't support the shortcuts for changing color. Nor can it be activated since it doesn't run as normal process. Microsoft has made it completely unmanageable now.

**Pull request merged**
